apiVersion: apps/v1
kind: Deployment
metadata:
  name: favorite-service-8013
  namespace: gjw-24-06-27
  labels:
    app: favorite-service-8013
spec:
  replicas: 1
  selector:
    matchLabels:
      app: favorite-service-8013
  template:
    metadata:
      name: favorite-service-8013
      labels:
        app: favorite-service-8013
    spec:
      containers:
        - name: favorite-service-8013
          image: favorite-service-8013:24.07.13
          imagePullPolicy: Never
          ports:
            - containerPort: 8013
      nodeSelector:
        preferrednode: node1
---
apiVersion: v1
kind: Service
metadata:
  name: favorite-service-8013
  namespace: gjw-24-06-27
spec:
  type: NodePort
  selector:
    app: favorite-service-8013
  ports:
    - protocol: TCP
      port: 8013
      targetPort: 8013
