apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad-service-8002
  namespace: gjw-24-06-27
  labels:
    app: ad-service-8002
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ad-service-8002
  template:
    metadata:
      name: ad-service-8002
      labels:
        app: ad-service-8002
    spec:
      containers:
        - name: ad-service-8002
          image: 10.69.37.140:5000/ad-service-8002:24.07.13
          imagePullPolicy: Never
          ports:
            - containerPort: 8002
      nodeSelector:
        preferrednode: node2
---
apiVersion: v1
kind: Service
metadata:
  name: ad-service-8002
  namespace: gjw-24-06-27
spec:
  type: NodePort
  selector:
    app: ad-service-8002
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
      