apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-service-8009
  namespace: gjw-24-06-27
  labels:
    app: message-service-8009
spec:
  replicas: 1
  selector:
    matchLabels:
      app: message-service-8009
  template:
    metadata:
      name: message-service-8009
      labels:
        app: message-service-8009
    spec:
      containers:
        - name: message-service-8009
          image: message-service-8009:24.06.28
          imagePullPolicy: Never
          ports:
            - containerPort: 8009
      nodeSelector:
        preferrednode: node1
---
apiVersion: v1
kind: Service
metadata:
  name: message-service-8009
  namespace: gjw-24-06-27
spec:
  type: NodePort
  selector:
    app: message-service-8009
  ports:
    - protocol: TCP
      port: 8009
      targetPort: 8009