apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommend-service-8003
  namespace: gjw-24-06-27
  labels:
    app: recommend-service-8003
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommend-service-8003
  template:
    metadata:
      name: recommend-service-8003
      labels:
        app: recommend-service-8003
    spec:
      containers:
        - name: recommend-service-8003
          image: recommend-service-8003:24.06.28
          imagePullPolicy: Never
          ports:
            - containerPort: 8003
---
apiVersion: v1
kind: Service
metadata:
  name: recommend-service-8003
  namespace: gjw-24-06-27
spec:
  type: NodePort
  selector:
    app: recommend-service-8003
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
