apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscribe-service-8012
  namespace: gjw-24-06-27
  labels:
    app: subscribe-service-8012
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscribe-service-8012
  template:
    metadata:
      name: subscribe-service-8012
      labels:
        app: subscribe-service-8012
    spec:
      containers:
        - name: subscribe-service-8012
          image: subscribe-service-8012:24.07.13
          imagePullPolicy: Never
          ports:
            - containerPort: 8012
      nodeSelector:
        preferrednode: node1
---
apiVersion: v1
kind: Service
metadata:
  name: subscribe-service-8012
  namespace: gjw-24-06-27
spec:
  type: NodePort
  selector:
    app: subscribe-service-8012
  ports:
    - protocol: TCP
      port: 8012
      targetPort: 8012
