spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mini1?serverTimezone=UTC
    #    url: jdbc:mysql://localhost:3306/mini1?serverTimezone=Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

