apiVersion: apps/v1
kind: Deployment
metadata:
  name: fronted-service-8001
  namespace: gjw-24-06-27
  labels:
    app: fronted-service-8001
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fronted-service-8001
  template:
    metadata:
      name: fronted-service-8001
      labels:
        app: fronted-service-8001
    spec:
      containers:
        - name: fronted-service-8001
          image: fronted-service-8001:24.06.28
          imagePullPolicy: Never
          ports:
            - containerPort: 8001
      nodeSelector:
        preferrednode: node3
---
apiVersion: v1
kind: Service
metadata:
  name: fronted-service-8001
  namespace: gjw-24-06-27
spec:
  type: NodePort
  selector:
    app: fronted-service-8001
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
