apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-service-8008
  namespace: gjw-24-06-27
  labels:
    app: member-service-8008
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member-service-8008
  template:
    metadata:
      name: member-service-8008
      labels:
        app: member-service-8008
    spec:
      containers:
        - name: member-service-8008
          image: member-service-8008:24.06.28
          imagePullPolicy: Never
          ports:
            - containerPort: 8008
      nodeSelector:
        preferrednode: node1
---
apiVersion: v1
kind: Service
metadata:
  name: member-service-8008
  namespace: gjw-24-06-27
spec:
  type: NodePort
  selector:
    app: member-service-8008
  ports:
    - protocol: TCP
      port: 8008
      targetPort: 8008
