apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-8006
  namespace: gjw-24-06-27
  labels:
    app: order-service-8006
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service-8006
  template:
    metadata:
      name: order-service-8006
      labels:
        app: order-service-8006
    spec:
      containers:
        - name: order-service-8006
          image: order-service-8006:24.07.13
          imagePullPolicy: Never
          ports:
            - containerPort: 8006
      nodeSelector:
        preferrednode: node1
---
apiVersion: v1
kind: Service
metadata:
  name: order-service-8006
  namespace: gjw-24-06-27
spec:
  type: NodePort
  selector:
    app: order-service-8006
  ports:
    - protocol: TCP
      port: 8006
      targetPort: 8006